### ISSUE TITLE
Feature Request: Do not present results before vote

### ISSUE THREAD

**Issue by joobei** [fsinfuhh/Bitpoll#12]
Prior votes seem to be influencing bitpoll participants so it would be nice if there was an option that you had to vote before you see the poll results. 

I'm not exactly sure how this would work for anonymous users (ones that are not logged in). I guess you'd need to store it in a cookie, that they have already voted for this specific poll so that they can see the results if they revisit in the future.

Would be a great feature to have.

**Comment by lsbloxx** [comment]
after you have created a poll appears an option called "Show Results" in the poll settings. there you have various choices, e.g. "summary/complete after vote". this may be the feature you are looking for. please let me know. :)

hint: this feature could work not as expected when users are not logged in/anonymous.

**Comment by Akasch** [comment]
in 2ec382d3e28c693a39c1e319d38268a86d5313f4 I have fixed that the owner can not see the results in the restricted "Show Results" settings, as I thing they are pretty useless if the creator can not see the results.

I will close this because I think it is the option you wanted, if there is something missing feel free to comment/reopen
